/* =============================================================================
   i18n adapter
   -----------------------------------------------------------------------------
   This file used to hold the entire dictionary tree inline. It is now a thin
   adapter over `site.config.ts`. The shape (Dictionary type) is preserved so
   that every component reading `dict.foo.bar` keeps working — only the source
   of the values has moved.

   When deriving a new site from this template, DO NOT edit this file.
   Edit `src/site.config.ts` instead.
   ========================================================================== */

import {
  siteConfig,
  CATEGORY_ORDER,
  normalizeCategory,
  categoryNames
} from "@/site.config";
import type { Lang, CategoryKey } from "@/site.config";

export type { Lang, CategoryKey };
export { CATEGORY_ORDER, normalizeCategory };

export type Dictionary = {
  brand: { tagline: string; legal: string };
  nav: {
    home: string;
    about: string;
    subscribe: string;
  };
  ui: {
    readMore: string;
    by: string;
    minRead: string;
    featured: string;
    latest: string;
    related: string;
    backToHome: string;
    issue: string;
    moreIn: string;
    newsletter: {
      eyebrow: string;
      heading: string;
      lede: string;
      placeholder: string;
      cta: string;
      disclaimer: string;
    };
    footer: {
      sections: { name: string; items: string[] }[];
      copy: string;
    };
    languageToggle: { label: string };
    notFound: { title: string; lede: string; back: string };
    /** Optional brand CTA (e.g. Submit Tool on AITECH). Resolved from
     *  siteConfig.brand.cta when present; undefined on sister titles
     *  that don't declare a CTA. */
    cta?: { label: string; href: string; hint: string };
  };
  categories: Record<CategoryKey, string>;
};

/** Pull a bilingual field out of siteConfig for a given language. */
const pick = <T,>(b: { en: T; ja: T }, lang: Lang): T => b[lang];

/** Build the dictionary for one language from siteConfig. */
function buildDictionary(lang: Lang): Dictionary {
  const sc = siteConfig;
  const chrome = sc.chrome;
  return {
    brand: {
      tagline: pick(chrome.tagline, lang),
      legal: pick(chrome.legal, lang)
    },
    nav: {
      home: pick(chrome.nav.home, lang),
      about: pick(chrome.nav.about, lang),
      subscribe: pick(chrome.nav.subscribe, lang)
    },
    ui: {
      readMore: pick(chrome.ui.readMore, lang),
      by: pick(chrome.ui.by, lang),
      minRead: pick(chrome.ui.minRead, lang),
      featured: pick(chrome.ui.featured, lang),
      latest: pick(chrome.ui.latest, lang),
      related: pick(chrome.ui.related, lang),
      backToHome: pick(chrome.ui.backToHome, lang),
      issue: pick(chrome.ui.issue, lang),
      moreIn: pick(chrome.ui.moreIn, lang),
      newsletter: {
        eyebrow: pick(chrome.newsletter.eyebrow, lang),
        heading: pick(chrome.newsletter.heading, lang),
        lede: pick(chrome.newsletter.lede, lang),
        placeholder: pick(chrome.newsletter.placeholder, lang),
        cta: pick(chrome.newsletter.cta, lang),
        disclaimer: pick(chrome.newsletter.disclaimer, lang)
      },
      footer: {
        // `sections` is preserved for back-compat; modern Footer reads
        // CATEGORY_ORDER + dict.categories directly, so this is dead-data
        // but type-shape stays stable.
        sections: [
          {
            name: lang === "ja" ? "セクション" : "Sections",
            items: CATEGORY_ORDER.map((k) => pick(categoryNames[k], lang))
          },
          {
            name: lang === "ja" ? "編集部" : "Editorial",
            items: [pick(chrome.nav.about, lang), pick(chrome.nav.subscribe, lang)]
          }
        ],
        copy: pick(chrome.footer.copy, lang)
      },
      languageToggle: { label: pick(chrome.languageToggle, lang) },
      notFound: {
        title: pick(chrome.notFound.title, lang),
        lede: pick(chrome.notFound.lede, lang),
        back: pick(chrome.notFound.back, lang)
      },
      // Optional CTA — only present when siteConfig.brand.cta is declared.
      // ADVERTISE TOKYO omits it; AITECH TOKYO declares it. We cast through
      // a loose shape so the `as const` literal type of siteConfig (which
      // strips the property when omitted) doesn't reject the access — we
      // verify presence at runtime via the truthy check.
      ...(() => {
        const brandWithOptionalCta = sc.brand as {
          cta?: {
            label: { en: string; ja: string };
            href: string;
            hint: { en: string; ja: string };
          };
        };
        const cta = brandWithOptionalCta.cta;
        return cta
          ? {
              cta: {
                label: pick(cta.label, lang),
                href: cta.href,
                hint: pick(cta.hint, lang)
              }
            }
          : {};
      })()
    },
    categories: Object.fromEntries(
      CATEGORY_ORDER.map((k) => [k, pick(categoryNames[k], lang)])
    ) as Record<CategoryKey, string>
  };
}

export const dictionaries: Record<Lang, Dictionary> = {
  en: buildDictionary("en"),
  ja: buildDictionary("ja")
};

export const isLang = (v: unknown): v is Lang => v === "en" || v === "ja";
